name: anti_captivate
description: Bypass the captive portal in Hungarian schools

version: 0.4.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  connectivity: ^0.4.2+2
  http: ^0.12.0+2
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true